name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: main.bicep
          outputFilePath: azuredeploy.json
      - name: Git CheckIn
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Bicep Built"
          add: '.'
